services:
  app:
    container_name: meduzzen-back-app-dev
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /node_modules
    ports:
      - "8080:8080"
    command: npm run start:dev

  test:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /node_modules
    command: npm run test

  test-cov:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /node_modules
      - ./coverage:/app/coverage
    command: npm run test:cov

  test-e2e:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /node_modules
    command: npm run test:e2e