services:
  app:
    container_name: meduzzen-back-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    depends_on:
      test:
        condition: service_completed_successfully
      test-e2e:
        condition: service_completed_successfully

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run test

  test-cov:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./coverage:/app/coverage
    command: npm run test:cov

  test-e2e:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run test:e2e